# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: dhoondlai
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: scrapers
# "service" is the name of this project. This will also be added to your AWS resource names.
service: scrapers

provider:
  name: aws
  runtime: python3.8
  timeout: 900

functions:
  techmatched:
    handler: scrapers/techmatched.run
    name: Techmatched scraper
    events:
      - schedule: rate(1 day)
  junaidtech:
    handler: scrapers/junaidtech.run
    name: Junaidtech scraper
    events:
      - schedule: rate(1 day)
plugins:
  - serverless-python-requirements
